menu/src/Entity/Gerecht.php
<?php

namespace App\Entity;

use App\Repository\GerechtRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: GerechtRepository::class)]
class Gerecht
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $gerecht;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $beschrijving;

    #[ORM\Column(type: 'float', nullable: true)]
    private $Prijs;

    #[ORM\Column(type: 'string', length: 225, nullable: true)]
    private $image;

    #[ORM\ManyToOne(targetEntity: 'App\Entity\Categorie', inversedBy: 'gerecht')]
    private $categorie;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getGerecht(): ?string
    {
        return $this->gerecht;
    }

    public function setGerecht(string $gerecht): self
    {
        $this->gerecht = $gerecht;

        return $this;
    }

    public function getBeschrijving(): ?string
    {
        return $this->beschrijving;
    }

    public function setBeschrijving(?string $beschrijving): self
    {
        $this->beschrijving = $beschrijving;

        return $this;
    }

    public function getPrijs(): ?float
    {
        return $this->Prijs;
    }

    public function setPrijs(?float $Prijs): self
    {
        $this->Prijs = $Prijs;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getCategorie(): ?Categorie
    {
        return $this->categorie;
    }

    public function setCategorie(?Categorie $categorie): self
    {
        $this->categorie = $categorie;

        return $this;
    }
}

menu/src/Controller/GerechtenController.php
<?php

namespace App\Controller;

use App\Entity\Gerecht;
use App\Form\GerechtType;
use App\Repository\GerechtRepository;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/gerechten', name: 'gerechten.')]
class GerechtenController extends AbstractController
{
    #[Route('/', name: 'aanpassen')]
    public function index(GerechtRepository $gerechtenData): Response
    {
        $gerechten = $gerechtenData->findAll();

        return $this->render('gerechten/index.html.twig', [
            'gerechten' => array_reverse($gerechten),
        ]);
    }

    #[Route('/maak', name: 'maak')]
    public function create(Request $request, ManagerRegistry $doctrine)
    {
        $gerecht = new Gerecht();

        //Form 
        $form = $this->createForm(GerechtType::class, $gerecht);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            //Entity manager
            $em = $doctrine->getManager();
            $image = $request->files->get('gerecht')['image'];

            if ($image) {
                $imageName = md5(uniqid()) . '.' . $image->guessClientExtension();
            }

            $image->move(
                $this->getParameter('images_folder'),
                $imageName
            );

            $gerecht->setImage($imageName);

            $em->persist($gerecht);
            $em->flush();

            return $this->redirect($this->generateUrl('gerechten.aanpassen'));
        }

        //Response 
        return $this->render('gerechten/maak.html.twig', [
            'gerechtForm' => $form->createView()
        ]);
    }

    #[Route('/delete{id}', name: 'delete')]
    public function delete($id, GerechtRepository $gerechtData, ManagerRegistry $doctrine)
    {
        $em = $doctrine->getManager();
        $gerecht = $gerechtData->find($id);
        $em->remove($gerecht);
        $em->flush();

        $this->addFlash('succes', "Gerecht is succesvol verwijderd");

        return $this->redirect($this->generateUrl('gerechten.aanpassen'));
    }

    #[Route('/show{id}', name: 'show')]
    public function showPicture(Gerecht $gerecht)
    {
        return $this->render('gerechten/showImage.html.twig', [
            'gerecht' => $gerecht,
        ]);
    }
}

menu/templates/gerechten/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Gerechten
{% endblock %}

{% block body %}
	{% for message in app.flashes('succes') %}
		<div data-closable class="alert-box callout success">
			<i class="fa fa-check"></i>
			{{ message }}
			<button class="close-button" aria-label="Dismiss alert" type="button" data-close>
				<span aria-hidden="true">&CircleTimes;</span>
			</button>
		</div>
	{% endfor %}
	<h2 class="grid-x align-center">Pas menu aan</h2>
	<br>
	<ul class="stats-list">
		<li>
			Gerechten
			<span class="stats-list-label">
				{{gerechten|length}}</span>
		</li>
		{% if gerechten|length > 0 %}
			<li class="stats-list-positive">
				Laatst toegevoegd
				<span class="stats-list-label">{{gerechten[0].gerecht}}</span>
			</li>
		{% endif %}
		<li class="stats-list-positive">
			Nieuw gerecht
			<span class="stats-list-label">
				<a href="{{ path('gerechten.maak')}}">Voeg toe</a>
			</span>
		</li>
	</ul>
	<table>
		<thead>
			<tr>
				<th width="50">ID</th>
				<th>Beschrijving</th>
				<th width="100">Soort</th>
				<th width="150">Gerecht</th>
				<th width="150">€</th>
				<th width="150">Delete</th>
				<th width="120">Image</th>
			</tr>
		</thead>
		<tbody>
			{% if gerechten|length > 0 %}
				{% for gerecht in gerechten%}
					<tr>
						<td>{{gerecht.id}}</td>
						<td>{{gerecht.beschrijving}}</td>
						<td>{{gerecht.categorie}}</td>
						<td>{{gerecht.gerecht}}</td>
						<td>{{gerecht.prijs}}</td>
						<td>
							<a href="{{ path('gerechten.delete',{id: gerecht.id})}}">Delete</a>
						</td>
						<td>
							<a href="{{ path('gerechten.show',{id: gerecht.id})}}">
								<i class="fa fa-solid fa-eye"></i>
							</a>
						</td>
					</tr>
				{% endfor %}
			{% endif %}
		</tbody>
	</table>
{% endblock %}

menu/templates/gerechten/maak.html.twig
{% extends 'base.html.twig' %}

{% block title %}Maak Gerecht
{% endblock %}

{% block body %}
	<h2 class="grid-x align-center">Pas menu aan</h2>
	<br>

	<div class="grid-x align-center">
		<div class="cell small-4">
			{{form(gerechtForm)}}
			</div>
		</div>
	{% endblock %}

menu/templates/gerechten/showImage.html.twig
{% extends 'base.html.twig' %}

{% block title %}Image
{% endblock %}

{% block body %}
	<h2 class="grid-x align-center">{{gerecht.gerecht}}</h2>
	<br>

	<div class="grid-x align-center">
		<div class="cell small-4">
			<img src="{{asset('images/' ~ gerecht.image)}}" alt="Foto van {{gerecht.gerecht}}">
		</div>
	</div>
	<br>

{% endblock %}